name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: nara-backend-api
  REGION: us-central1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Force use Node 24

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update ke v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2 # Update ke v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2 # Update ke v2

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}"
          docker build -t $IMAGE_PATH .
          docker push $IMAGE_PATH

      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_PATH \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }} \
            --set-env-vars MIXPANEL_TOKEN=${{ secrets.MIXPANEL_TOKEN }} \
            --set-env-vars MIXPANEL_API_SECRET=${{ secrets.MIXPANEL_API_SECRET }} \
            --set-env-vars ONESIGNAL_APP_ID=${{ secrets.ONESIGNAL_APP_ID }} \
            --set-env-vars ONESIGNAL_API_KEY=${{ secrets.ONESIGNAL_API_KEY }} \
            --set-env-vars GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --set-env-vars NARA_ADMIN_API_KEY=${{ secrets.NARA_ADMIN_API_KEY }} \
            --set-env-vars GCP_QUEUE_NAME=nara-campaign-queue \
            --set-env-vars GCP_LOCATION=${{ env.REGION }}